import { Component, OnInit, ElementRef, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CreatorService } from '../../services/creator.service';

@Component({
  selector: 'app-creator-ai-tools',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './creator-ai-tools.component.html',
  styleUrls: ['../creator-shared.css', './creator-ai-tools.component.css'],
})
export class CreatorAiToolsComponent implements OnInit {
  @ViewChild('fileInput') fileInput!: ElementRef<HTMLInputElement>;

  /* ── State ──────────────────────────────────────────────────── */
  suggestions:      any[] = [];
  savedSuggestions: any[] = [];
  loading    = true;
  generating = false;
  saving     = false;
  activeTab: 'generate' | 'titles' | 'hashtags' | 'upload' | 'saved' = 'generate';
  editId      = '';
  editContent = '';
  toast = { show: false, msg: '', type: 'success' };

  /* ── Live result panel (shown immediately after generation) ─── */
  liveResult: any = null;

  /* ── Generate form ──────────────────────────────────────────── */
  form: any = { type: 'full_post', prompt: '', platform: 'Instagram', niche: 'Fashion' };
  aiTypes   = ['caption', 'hashtags', 'content_idea', 'full_post'];
  platforms = ['Instagram', 'YouTube', 'TikTok', 'Twitter', 'Blog'];
  niches    = ['Fashion','Beauty','Tech','Gaming','Food','Travel','Fitness','Lifestyle'];

  /* ── Title generator ────────────────────────────────────────── */
  titleForm       = { topic: '', platform: 'Instagram', niche: 'Fashion', count: 5 };
  titleResults:   any[] = [];
  titlesLoading   = false;
  titleCopied     = '';

  /* ── Hashtag generator ──────────────────────────────────────── */
  hashtagForm     = { topic: '', platform: 'Instagram', niche: 'Fashion', count: 20 };
  hashtagResults: any[] = [];
  hashtagsLoading = false;
  hashtagFilter: 'all' | 'trending' | 'niche' | 'community' = 'all';
  copiedHashtag   = '';

  /* ── Upload & analyse ───────────────────────────────────────── */
  uploadForm  = { platform: 'Instagram', niche: 'Fashion', contentDescription: '' };
  uploadFile: File | null = null;
  uploadPreview: string | null = null;
  uploadFileType: 'image' | 'video' | 'text' | null = null;
  uploadAnalysis: any = null;
  uploadLoading  = false;
  isDragOver     = false;

  constructor(private creator: CreatorService) {}

  ngOnInit(): void { this.load(); }

  /* ── Load history ───────────────────────────────────────────── */
  load(): void {
    this.loading = true;
    this.creator.getAiSuggestions().subscribe({
      next: (r: any) => {
        this.suggestions      = r.suggestions || [];
        this.savedSuggestions = this.suggestions.filter((s: any) => s.isSaved);
        this.loading          = false;
      },
      error: () => { this.loading = false; },
    });
  }

  /* ── Full generate — show result immediately from response ──── */
  generate(): void {
    if (!this.form.prompt.trim()) {
      this.showToast('Please enter a topic or prompt first', 'error');
      return;
    }
    this.generating = true;
    this.liveResult = null;
    this.creator.generateAiSuggestion(this.form).subscribe({
      next: (r: any) => {
        // Show AI content immediately from the API response
        this.liveResult = r.suggestion;
        this.generating = false;
        this.load(); // also refresh history in background
        this.showToast('Content generated by Gemini AI! ✨');
      },
      error: (e: any) => {
        this.generating = false;
        this.showToast(e?.error?.message || 'Generation failed. Check your API key.', 'error');
      },
    });
  }

  clearLiveResult(): void { this.liveResult = null; }

  /* ── Title generator ────────────────────────────────────────── */
  generateTitles(): void {
    this.titlesLoading = true;
    this.titleResults  = [];
    this.creator.generateTitles(this.titleForm).subscribe({
      next: (r: any) => {
        this.titleResults  = r.titles || [];
        this.titlesLoading = false;
        if (!this.titleResults.length) this.showToast('No titles returned, try again', 'error');
      },
      error: (e: any) => {
        this.titlesLoading = false;
        this.showToast(e?.error?.message || 'Could not generate titles', 'error');
      },
    });
  }

  copyTitle(t: any): void {
    navigator.clipboard.writeText(t.title);
    this.titleCopied = t.title;
    this.showToast('Title copied!');
    setTimeout(() => this.titleCopied = '', 2000);
  }

  /* ── Hashtag generator ──────────────────────────────────────── */
  generateHashtags(): void {
    this.hashtagsLoading = true;
    this.hashtagResults  = [];
    this.creator.generateHashtags(this.hashtagForm).subscribe({
      next: (r: any) => {
        this.hashtagResults  = r.hashtags || [];
        this.hashtagsLoading = false;
        if (!this.hashtagResults.length) this.showToast('No hashtags returned, try again', 'error');
      },
      error: (e: any) => {
        this.hashtagsLoading = false;
        this.showToast(e?.error?.message || 'Could not generate hashtags', 'error');
      },
    });
  }

  get filteredHashtags(): any[] {
    if (this.hashtagFilter === 'all') return this.hashtagResults;
    return this.hashtagResults.filter((h: any) => h.category === this.hashtagFilter);
  }

  copyAllHashtags(): void {
    const tags = this.filteredHashtags.map((h: any) => h.tag).join(' ');
    navigator.clipboard.writeText(tags);
    this.showToast(this.filteredHashtags.length + ' hashtags copied!');
  }

  copyHashtag(tag: string): void {
    navigator.clipboard.writeText(tag);
    this.copiedHashtag = tag;
    setTimeout(() => this.copiedHashtag = '', 1500);
  }

  reachColor(reach: string): string {
    const map: any = { massive: 'pill-rose', large: 'pill-amber', medium: 'pill-sky', niche: 'pill-jade' };
    return map[reach] || 'pill-gray';
  }

  /* ── File upload ────────────────────────────────────────────── */
  onFileChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files?.length) this.setFile(input.files[0]);
  }

  onDrop(e: DragEvent): void {
    e.preventDefault();
    this.isDragOver = false;
    const file = e.dataTransfer?.files[0];
    if (file) this.setFile(file);
  }

  setFile(file: File): void {
    this.uploadFile = file;
    const mime = file.type;
    if (mime.startsWith('image/'))      this.uploadFileType = 'image';
    else if (mime.startsWith('video/')) this.uploadFileType = 'video';
    else                                this.uploadFileType = 'text';
    if (this.uploadFileType === 'image') {
      const reader = new FileReader();
      reader.onload = (ev: any) => this.uploadPreview = ev.target.result;
      reader.readAsDataURL(file);
    } else {
      this.uploadPreview = null;
    }
    this.uploadAnalysis = null;
  }

  removeUpload(): void {
    this.uploadFile = null; this.uploadPreview = null;
    this.uploadFileType = null; this.uploadAnalysis = null;
    if (this.fileInput) this.fileInput.nativeElement.value = '';
  }

  analyzeContent(): void {
    this.uploadLoading  = true;
    this.uploadAnalysis = null;
    const fd = new FormData();
    if (this.uploadFile) fd.append('mediaFile', this.uploadFile);
    fd.append('platform',           this.uploadForm.platform);
    fd.append('niche',              this.uploadForm.niche);
    fd.append('contentDescription', this.uploadForm.contentDescription || (this.uploadFile?.name || ''));
    fd.append('fileType',           this.uploadFileType || 'content');
    this.creator.analyzeUploadedContent(fd).subscribe({
      next: (r: any) => {
        this.uploadAnalysis = r.analysis;
        this.uploadLoading  = false;
        this.showToast('Content analysed by Gemini AI! ✨');
        this.load();
      },
      error: (e: any) => {
        this.uploadLoading = false;
        this.showToast(e?.error?.message || 'Analysis failed', 'error');
      },
    });
  }

  copyAnalysisCaption(): void {
    if (this.uploadAnalysis?.suggestedCaption) {
      navigator.clipboard.writeText(this.uploadAnalysis.suggestedCaption);
      this.showToast('Caption copied!');
    }
  }

  copyAnalysisHashtags(): void {
    if (!this.uploadAnalysis?.suggestedHashtags?.length) return;
    const tags = this.uploadAnalysis.suggestedHashtags.map((h: any) => h.tag || h).join(' ');
    navigator.clipboard.writeText(tags);
    this.showToast(this.uploadAnalysis.suggestedHashtags.length + ' hashtags copied!');
  }

  /* ── Edit / save existing ───────────────────────────────────── */
  startEdit(s: any): void {
    this.editId      = s._id;
    this.editContent = s.editedContent || s.generatedCaption || s.contentIdea || '';
  }

  saveEdit(): void {
    this.saving = true;
    this.creator.updateAiSuggestion(this.editId, { editedContent: this.editContent, isSaved: true }).subscribe({
      next: () => { this.load(); this.editId = ''; this.saving = false; this.showToast('Saved!'); },
      error: ()  => { this.saving = false; this.showToast('Error saving', 'error'); },
    });
  }

  remove(id: string): void {
    if (this.liveResult?._id === id) this.liveResult = null;
    this.creator.deleteAiSuggestion(id).subscribe({
      next: () => { this.load(); this.showToast('Removed.'); },
      error: () => {},
    });
  }

  copy(text: string): void {
    if (!text) return;
    navigator.clipboard.writeText(text);
    this.showToast('Copied to clipboard!');
  }

  ctrColor(score: number): string {
    if (score >= 8) return '#34D399';
    if (score >= 6) return '#FBBF24';
    return '#FB7185';
  }

  ctrBg(score: number): string {
    if (score >= 8) return 'rgba(52,211,153,.12)';
    if (score >= 6) return 'rgba(251,191,36,.12)';
    return 'rgba(251,113,133,.12)';
  }

  showToast(msg: string, type: 'success' | 'error' = 'success'): void {
    this.toast = { show: true, msg, type };
    setTimeout(() => this.toast.show = false, 3500);
  }
}